title: "Pawel Wilczewski"
author: "Pawel Wilczewski"
description: "&copy; Pawel Wilczewski 2022"
permalink: /:categories/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%Y"         # default: "%B %d, %Y"

# Layout

show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

icons:                     # additional icons that can be used in the text
  - {icon: keyboard}
  - {icon: location-dot}

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "commercial.html"}
  - {file: "personal.html"}
  - {file: "university.html"}
  # - {file: "categories.html"}
  # - {file: "about.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {icon: envelope, url: "mailto:pawel.wilczewski@outlook.com"}
  - {icon: github, url: "https://github.com/pawelwilczewski"}
  - {icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
