title: "Pawel Wilczewski"
author: "Pawel Wilczewski"
permalink: /:categories/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%Y"         # default: "%B %d, %Y"

icons:                     # additional icons that can be used in the text across the website
  - {icon: keyboard}
  - {icon: location-dot}
  - {icon: c}
  - {icon: file}
  - {icon: code}
  - {icon: house}

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "commercial.html", icon: "sack-dollar", title: "Commercial Projects"}
  - {file: "personal.html", icon: "person", title: "Personal Projects"}
  - {file: "university.html", icon: "building-columns", title: "University Projects"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {icon: envelope, url: "mailto:pawel.wilczewski@outlook.com"}
  - {icon: linkedin, url: "https://www.linkedin.com/in/pawel-wilczewski"}
  - {icon: github, url: "https://github.com/pawelwilczewski"}
  - {icon: gitlab, url: "https://gitlab.com/Pawel_Wilczewski"}
  - {icon: artstation, url: "https://www.artstation.com/pawelwilczewski"}
  - {icon: youtube, url: "https://www.youtube.com/channel/UCOznVhJ7YslS1JAAl18K5xA"}
  - {icon: rss, url: "/feed.xml"}

plugins:
 - jekyll-feed
